name: Deploy to Lovable

on:
  push:
    branches:
      - main  # Change to your deploy branch if needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Lovable
        run: |
          curl -X POST https://api.lovable.so/deploy \
            -H "Authorization: Bearer ${{ secrets.LOVABLE_API_KEY }}" \
            -H "Content-Type: application/json" \
            -d '{"branch":"main"}'
